module.exports = [ { meaning: 'd a n c e',
    word: 'bailar',
    conj:
     { '3p': 'bailan',
       '2s': 'bailas',
       '3s': 'baila',
       '1p': 'bailamos',
       '2p': 'bailáis',
       '1s': 'bailo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to search for, look for',
    word: 'buscar',
    conj:
     { '3p': 'buscan',
       '2s': 'buscas',
       '3s': 'busca',
       '1p': 'buscamos',
       '2p': 'buscáis',
       '1s': 'busco',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to walk, go',
    word: 'caminar',
    conj:
     { '3p': 'caminan',
       '2s': 'caminas',
       '3s': 'camina',
       '1p': 'caminamos',
       '2p': 'camináis',
       '1s': 'camino',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to buy, purchase',
    word: 'comprar',
    conj:
     { '3p': 'compran',
       '2s': 'compras',
       '3s': 'compra',
       '1p': 'compramos',
       '2p': 'compráis',
       '1s': 'compro',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to answer',
    word: 'contestar',
    conj:
     { '3p': 'contestan',
       '2s': 'contestas',
       '3s': 'contesta',
       '1p': 'contestamos',
       '2p': 'contestáis',
       '1s': 'contesto',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to talk, converse; to tell, relate',
    word: 'conversar',
    conj:
     { '3p': 'conversan',
       '2s': 'conversas',
       '3s': 'conversa',
       '1p': 'conversamos',
       '2p': 'conversáis',
       '1s': 'converso',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to rest, take a rest; to support, lean [on',
    word: 'descansar',
    conj:
     { '3p': 'descansan',
       '2s': 'descansas',
       '3s': 'descansa',
       '1p': 'descansamos',
       '2p': 'descansáis',
       '1s': 'descanso',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to desire, want, wish',
    word: 'desear',
    conj:
     { '3p': 'desean',
       '2s': 'deseas',
       '3s': 'desea',
       '1p': 'deseamos',
       '2p': 'deseáis',
       '1s': 'deseo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to draw, sketch, depict',
    word: 'dibujar',
    conj:
     { '3p': 'dibujan',
       '2s': 'dibujas',
       '3s': 'dibuja',
       '1p': 'dibujamos',
       '2p': 'dibujáis',
       '1s': 'dibujo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to listen to, hear',
    word: 'escuchar',
    conj:
     { '3p': 'escuchan',
       '2s': 'escuchas',
       '3s': 'escucha',
       '1p': 'escuchamos',
       '2p': 'escucháis',
       '1s': 'escucho',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 't o   h o p e',
    word: 'esperar',
    conj:
     { '3p': 'esperan',
       '2s': 'esperas',
       '3s': 'espera',
       '1p': 'esperamos',
       '2p': 'esperáis',
       '1s': 'espero',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to be',
    word: 'estar',
    conj:
     { '3p': 'están',
       '2s': 'estás',
       '3s': 'está',
       '1p': 'estamos',
       '2p': 'estáis',
       '1s': 'estoy',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to study',
    word: 'estudiar',
    conj:
     { '3p': 'estudian',
       '2s': 'estudias',
       '3s': 'estudia',
       '1p': 'estudiamos',
       '2p': 'estudiáis',
       '1s': 'estudio',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to explain',
    word: 'explicar',
    conj:
     { '3p': 'explican',
       '2s': 'explicas',
       '3s': 'explica',
       '1p': 'explicamos',
       '2p': 'explicáis',
       '1s': 'explico',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to please, be pleasing',
    word: 'gustar',
    conj:
     { '3p': 'gustan',
       '2s': 'gustas',
       '3s': 'gusta',
       '1p': 'gustamos',
       '2p': 'gustáis',
       '1s': 'gusto',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to speak',
    word: 'hablar',
    conj:
     { '3p': 'hablan',
       '2s': 'hablas',
       '3s': 'habla',
       '1p': 'hablamos',
       '2p': 'habláis',
       '1s': 'hablo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to arrive, come, reach; to bring up, bring over; to gather together',
    word: 'llegar',
    conj:
     { '3p': 'llegan',
       '2s': 'llegas',
       '3s': 'llega',
       '1p': 'llegamos',
       '2p': 'llegáis',
       '1s': 'llego',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to carry, bring',
    word: 'llevar',
    conj:
     { '3p': 'llevan',
       '2s': 'llevas',
       '3s': 'lleva',
       '1p': 'llevamos',
       '2p': 'lleváis',
       '1s': 'llevo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to watch, look at',
    word: 'mirar',
    conj:
     { '3p': 'miran',
       '2s': 'miras',
       '3s': 'mira',
       '1p': 'miramos',
       '2p': 'miráis',
       '1s': 'miro',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to need, require',
    word: 'necesitar',
    conj:
     { '3p': 'necesitan',
       '2s': 'necesitas',
       '3s': 'necesita',
       '1p': 'necesitamos',
       '2p': 'necesitáis',
       '1s': 'necesito',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to practice',
    word: 'practicar',
    conj:
     { '3p': 'practican',
       '2s': 'practicas',
       '3s': 'practica',
       '1p': 'practicamos',
       '2p': 'practicáis',
       '1s': 'practico',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to ask, inquire',
    word: 'preguntar',
    conj:
     { '3p': 'preguntan',
       '2s': 'preguntas',
       '3s': 'pregunta',
       '1p': 'preguntamos',
       '2p': 'preguntáis',
       '1s': 'pregunto',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to prepare, get',
    word: 'preparar',
    conj:
     { '3p': 'preparan',
       '2s': 'preparas',
       '3s': 'prepara',
       '1p': 'preparamos',
       '2p': 'preparáis',
       '1s': 'preparo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to return, go back',
    word: 'regresar',
    conj:
     { '3p': 'regresan',
       '2s': 'regresas',
       '3s': 'regresa',
       '1p': 'regresamos',
       '2p': 'regresáis',
       '1s': 'regreso',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to finish, end',
    word: 'terminar',
    conj:
     { '3p': 'terminan',
       '2s': 'terminas',
       '3s': 'termina',
       '1p': 'terminamos',
       '2p': 'termináis',
       '1s': 'termino',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to take, drink',
    word: 'tomar',
    conj:
     { '3p': 'toman',
       '2s': 'tomas',
       '3s': 'toma',
       '1p': 'tomamos',
       '2p': 'tomáis',
       '1s': 'tomo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to work',
    word: 'trabajar',
    conj:
     { '3p': 'trabajan',
       '2s': 'trabajas',
       '3s': 'trabaja',
       '1p': 'trabajamos',
       '2p': 'trabajáis',
       '1s': 'trabajo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to travel, journey',
    word: 'viajar',
    conj:
     { '3p': 'viajan',
       '2s': 'viajas',
       '3s': 'viaja',
       '1p': 'viajamos',
       '2p': 'viajáis',
       '1s': 'viajo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to learn',
    word: 'aprender',
    conj:
     { '3p': 'aprenden',
       '2s': 'aprendes',
       '3s': 'aprende',
       '1p': 'aprendemos',
       '2p': 'aprendéis',
       '1s': 'aprendo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to attend',
    word: 'asistir',
    conj:
     { '3p': 'asisten',
       '2s': 'asistes',
       '3s': 'asiste',
       '1p': 'asistimos',
       '2p': 'asistís',
       '1s': 'asisto',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to drink',
    word: 'beber',
    conj:
     { '3p': 'beben',
       '2s': 'bebes',
       '3s': 'bebe',
       '1p': 'bebemos',
       '2p': 'bebéis',
       '1s': 'bebo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to eat',
    word: 'comer',
    conj:
     { '3p': 'comen',
       '2s': 'comes',
       '3s': 'come',
       '1p': 'comemos',
       '2p': 'coméis',
       '1s': 'como',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to share; to divide [up]',
    word: 'compartir',
    conj:
     { '3p': 'comparten',
       '2s': 'compartes',
       '3s': 'comparte',
       '1p': 'compartimos',
       '2p': 'compartís',
       '1s': 'comparto',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to understand, comprehend',
    word: 'comprender',
    conj:
     { '3p': 'comprenden',
       '2s': 'comprendes',
       '3s': 'comprende',
       '1p': 'comprendemos',
       '2p': 'comprendéis',
       '1s': 'comprendo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to run',
    word: 'correr',
    conj:
     { '3p': 'corren',
       '2s': 'corres',
       '3s': 'corre',
       '1p': 'corremos',
       '2p': 'corréis',
       '1s': 'corro',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to owe; must, should, ought to',
    word: 'deber',
    conj:
     { '3p': 'deben',
       '2s': 'debes',
       '3s': 'debe',
       '1p': 'debemos',
       '2p': 'debéis',
       '1s': 'debo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to decide, settle, resolve',
    word: 'decidir',
    conj:
     { '3p': 'deciden',
       '2s': 'decides',
       '3s': 'decide',
       '1p': 'decidimos',
       '2p': 'decidís',
       '1s': 'decido',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to describe',
    word: 'describir',
    conj:
     { '3p': 'describen',
       '2s': 'describes',
       '3s': 'describe',
       '1p': 'describimos',
       '2p': 'describís',
       '1s': 'describo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to write',
    word: 'escribir',
    conj:
     { '3p': 'escriben',
       '2s': 'escribes',
       '3s': 'escribe',
       '1p': 'escribimos',
       '2p': 'escribís',
       '1s': 'escribo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to read',
    word: 'leer',
    conj:
     { '3p': 'leen',
       '2s': 'lees',
       '3s': 'lee',
       '1p': 'leemos',
       '2p': 'leéis',
       '1s': 'leo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to have',
    word: 'tener',
    conj:
     { '3p': 'tienen',
       '2s': 'tienes',
       '3s': 'tiene',
       '1p': 'tenemos',
       '2p': 'tenéis',
       '1s': 'tengo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to come',
    word: 'venir',
    conj:
     { '3p': 'vienen',
       '2s': 'vienes',
       '3s': 'viene',
       '1p': 'venimos',
       '2p': 'venís',
       '1s': 'vengo',
       mood: 'Indicative',
       tense: 'Present' } },
  { meaning: 'to live',
    word: 'vivir',
    conj:
     { '3p': 'viven',
       '2s': 'vives',
       '3s': 'vive',
       '1p': 'vivimos',
       '2p': 'vivís',
       '1s': 'vivo',
       mood: 'Indicative',
       tense: 'Present' } } ];